### ISSUE TITLE
tasks_retrieval/HPA_tasks_creation: file/folder name

### ISSUE THREAD

**Issue by qwu01** [BiomedSciAI/gene-benchmark#43]
Hi,
I encountered an issue when downloading tha task files using 
`python scripts/tasks_retrieval/HPA_tasks_creation.py --allow-downloads True` 
some times there's special characters like '|' that prevent you mkdir. 

```
Traceback (most recent call last):
  File "E:\projects\benchmark_1\gene-benchmark\scripts\tasks_retrieval\HPA_tasks_creation.py", line 110, in <module>
    main()
  File "E:\projects\benchmark_1\.venv\Lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\projects\benchmark_1\.venv\Lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "E:\projects\benchmark_1\.venv\Lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\projects\benchmark_1\.venv\Lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\projects\benchmark_1\gene-benchmark\scripts\tasks_retrieval\HPA_tasks_creation.py", line 106, in main
    create_tasks(data, main_task_directory, verbose)
  File "E:\projects\benchmark_1\gene-benchmark\scripts\tasks_retrieval\HPA_tasks_creation.py", line 59, in create_tasks
    dump_task_definitions(entities, outcomes, main_task_directory, task_name)
  File "E:\projects\benchmark_1\gene-benchmark\gene_benchmark\tasks.py", line 59, in dump_task_definitions
    task_dir_name.mkdir(exist_ok=True)
  File "C:\Users\accdd\AppData\Local\Programs\Python\Python311\Lib\pathlib.py", line 1116, in mkdir
    os.mkdir(self, mode)
OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: 'tasks\\Blood concentration - Conc. blood IM [pg|L]'
```

**Comment by yoavkt** [comment]
Hi,
Thank you for this issue.  Are you using a Windows machine?

**Comment by qwu01** [comment]
yes

**Comment by yoavkt** [comment]
So I created a branch that fixes this issue. the branch is workable but the PR is still waiting to be reviews.
You are welcome to review it and I will change it accordingly or a team member will review it soon.
